account/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views as auth_view
from . import views
from .forms import LoginForm

urlpatterns = [
		#path('login/', views.user_login, name = 'login')
		url(r'login', auth_view.LoginView.as_view(template_name = 'account/login.html', authentication_form = LoginForm), name = 'login'),
		url(r'logout', auth_view.LogoutView.as_view(template_name = 'account/logout.html'), name = 'logout'),
		url(r'dashboard', views.dashboard, name = 'dashboard'),
		url(r'password_change_done', auth_view.PasswordChangeDoneView.as_view(template_name = 'account/password_change_done.html'), name = 'password_change_done'),
		url(r'password_change', auth_view.PasswordChangeView.as_view(template_name = 'account/password_change.html', success_url = reverse_lazy('account:password_change_done')), name = 'password_change'),
		url(r'password_reset_done', auth_view.PasswordResetDoneView.as_view(template_name = 'account/password_reset_done.html'), name = 'password_reset_done'),
		url(r'password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name = 'account/password_reset_complete.html'), name = 'password_reset_complete'),
		re_path(r'password_reset_confirm_(?P<uidb64>[-\w]+)_(?P<token>[-\w]+)', auth_view.PasswordResetConfirmView.as_view(template_name = 'account/password_reset_confirm.html',  success_url = reverse_lazy('account:password_reset_complete')), name = 'password_reset_confirm'),
		url(r'password_reset', auth_view.PasswordResetView.as_view(template_name = 'account/password_reset_form.html', email_template_name = 'account/password_reset_email.html', success_url = reverse_lazy('account:password_reset_done')), name = 'password_reset'),
		path(r'register', views.register, name = 'register'),
		path(r'edit', views.edit, name = 'edit')
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'), namespace = 'account')),
    path('', include(('home.urls', 'home'), namespace = 'home')),
    path('social-auth/', include(('social_django.urls', 'social_django'), namespace = 'social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
		path('', views.home, name = 'home')
		]

account/models.py
from django.db import models
from django.conf import settings

class Profile (models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	date_of_birth = models.DateField(blank = True, null = True)
	photo = models.ImageField(upload_to = 'users/%Y/%m/%d', blank = True)

	def __str__ (self):
		return "Profile for user {}".format(self.user.username)

home/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile

class LoginForm (AuthenticationForm):
	username = forms.CharField(widget = forms.TextInput(attrs = {'placeholder': 'Username'}))
	password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder': 'Password'}))



class Register (forms.ModelForm):
	password1 = forms.CharField(label = 'Password', widget = forms.PasswordInput)
	password2 = forms.CharField(label = 'Repeat password', widget = forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'email')

	def clean_password2 (self):
		cd = self.cleaned_data
		if (cd['password1'] != cd['password2']):
			raise forms.ValidationError("Password dont match")
		return cd['password2']

class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
	class Meta:
		model= Profile
		fields = ('date_of_birth', 'photo')

account/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, Register, UserEditForm, ProfileEditForm
from .models import Profile
from django.contrib import messages
# Create your views here.


@login_required
def dashboard(request):
	return render(request, 'account/dashboard.html', {'section': 'dashboard'})

def register(request):
	if (request.method == 'POST'):
		user_form = Register(request.POST)
		if user_form.is_valid():
			new_user = user_form.save(commit = False)
			new_user.set_password(user_form.cleaned_data['password1'])
			new_user.save()
			profile = Profile.objects.create(user = new_user)
			return render(request, 'account/register_done.html', {'user': new_user})
	else:
		user_form = Register()
	return render(request, 'account/register.html', {'form': user_form})


@login_required
def edit(request):
	if request.method == "POST":
		user_form = UserEditForm(instance = request.user, data = request.POST)
		profile_form = ProfileEditForm(instance = request.user.profile,
									   data = request.POST,
									   files = request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Profile updated successfully')
		else:
			messages.error(request, 'Error updating your profile')
	else:
		user_form = UserEditForm(instance = request.user)
		profile_form = ProfileEditForm(instance = request.user.profile)
	context = {'user_form': user_form, 'profile_form': profile_form}
	return render(request, 'account/edit.html', context)

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
	return render(request, 'post/home.html')

account/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock %}</title>
	<link type = 'text/css' rel = 'stylesheet' href='{% static "css/base.css" %}'>
	<style>
		.menu .selected a
		{
			color: #316E38;
		}
	</style>
</head>
<body>
	<div id = 'header'>
		<span>
			<a class = "logo" style="text-decoration: none;"
			href = '{% url "home:home" %}'>
				Bookmarks
			</a>
		</span>
		{% if request.user.is_authenticated %}
			<span> <ul class = 'menu'>
				<li {% if section == 'dashboard' %}class = 'selected'{% endif %}>
					<a href="{% url 'account:dashboard' %}">My Dashboard</a></li>

				<li {% if section == 'images' %}class = 'selected'{% endif %}>
					<a href="{% url 'account:dashboard'%}">Images</a></li>

				<li {% if section == 'people' %}class = 'selected'{% endif %}>
					<a href="{% url 'account:dashboard'%}">People</a></li>
			</ul>
		</span>

		<span class = 'menu' style = 'margin-left: 150px;'>
				<li>Hello, {{request.user.first_name}}</li>
				<li><a href = '{% url "account:logout" %}'>Logout</a></li>
		</span>
		{% else %}
			<span class = 'something'>{% block something %} {% endblock %}</span>
		{% endif %}
	</div>
	<div id = 'content'>
		{% if messages %}
			<div class = 'mess'>
				{% for mess in messages %}
					<p>{{mess}}</p>
				{% endfor %}
			</div>
		{% endif%}
		{% block content %} {% endblock %}
	</div>
</body>
</html>

home/templates/base-home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock %}</title>
	<link type = 'text/css' rel = 'stylesheet' href='{% static "css/base-home.css" %}'>
		<style>
		{% if request.user.is_authenticated %}
		{% else %}
			body
			{
				background: url("{% static 'img/wall.jpg' %}") no-repeat;
				background-size: cover;
			}
		{% endif %}
		#button
		{
			display: inline-block;
			color: white;
			width: 300px;
			font-size: 18px;
			font-weight: bold;
			position: relative;
			left: 700px;
		}
		#button span
		{
			padding: 10px 30px;
			text-align: center;

		}
		#button span a
		{
			text-decoration: none;
			color: white;
		}
		.container
		{
			position: relative;
			z-index: 9;
		}

		.container:hover ul
		{
			display: block;
		}

		.container ul
		{
			display: none;
			position: absolute;
			background-color: #126635;
			color: white;
			list-style-type: none;
		}
		.container li
		{
			padding: 15px;
			border-bottom:1px solid white;
		}
	</style>
</head>
<body>
	<div id = 'header'>
		<span class = 'logo'><a href = "{% url 'home:home' %}" style = 'color:white; text-decoration: none;'>Bookmarks</a></span>
		{% block bar %}{% endblock %}
	</div>
	<div id = 'content'>
		{% block content %} {% endblock %}
	</div>
</body>
</html>

home/templates/post/home.html
{% extends 'base-home.html' %}

{% block title %}
	Home - Bookmarks
{% endblock %}

{% block bar%}
{% if request.user.is_authenticated %}

	<div id = 'button'>
		<span class = 'container'>
			Hello, {{ request.user.first_name }}
			<ul>
				<li><a href = "{% url 'account:dashboard'%}">My dashboard</a></li>
				<li><a href = '.'>People</a></li>
				<li><a href = '.'>Images</a></li>
				<li><a href = '{%url "account:password_change"%}'>Change password</a></li>
				<li><a href = "{% url 'account:logout' %}">Logout</a></li>
			</ul>
		</span>
	</div>
{% else %}
	<div id = 'button'>
			<span><a href= '{% url "account:login" %}'>Login</a></span>
			<span><a href = "{% url 'account:register'%}">Sign Up</a></span>
	</div>
{% endif %}
{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}

{% else %}
	<div style="background-color: #EFEFEF; opacity: 0.8; padding: 40px; margin-top: 100px; ">
		 <h1 style = 'width: 700px;
					  margin: 10px 250px;
					  margin-bottom: 10px;
					  color: white; 
					  font-size: 100px;
					  text-shadow: 1px 2px 4px black, -1px -2px 4px black'>Join me now</h1>

		<h3 style = 'width: 700px;
					  margin: 10px 400px; 
					  color: white; 
					  font-size: 30px;
					  text-shadow: 1px 2px 4px black, -1px -2px 4px black'>
					  Sign up free now to join us today</h3>
{% endif %}
</div>
{% endblock %}